# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libxml2-dev


before_install:
  - pip install numpy mwparserfromhell

env:
 global:
   - CRAN: http://cran.rstudio.com
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"  ## do not build vignettes or manual
    - _R_CHECK_TIMINGS_="0"  ## get the timing information for the examples for all of your functions

r_packages:
   - reticulate

r:
 - release

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings


notifications:
  email:
    on_failure: change
