# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
      - libxml2-dev

before_install:
  - pip install numpy pycompass

cran: http://cran.rstudio.com

r_packages:
   - reticulate

r:
 - release

# do not build vignettes...takes too long and times out on travis
r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

